name: balancer_management_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/th (1).jpg
    - assets/akar-icons_edit.png
    - assets/Group 1686553807.png
    - assets/adminphoto.jpg
    - assets/mdi_prize.png
    - assets/Frame 1000003263 1.png
    - assets/Filter.png

